AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-lambda-pipeline
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./search-lambda
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::032801474903:role/lambda-exec-role-for-lex"
      Environment:
        Variables:
          REGION: us-east-1
      Layers:
        - 'arn:aws:lambda:us-east-1:032801474903:layer:es:1'
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos-lambda-pipeline
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-lambda
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::032801474903:role/service-role/index-photos-role-hzfxnypz"
      Environment:
        Variables:
          REGION: us-east-1
      Layers:
        - 'arn:aws:lambda:us-east-1:032801474903:layer:es:1'
